# Generated by Django 4.2 on 2023-04-30 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
