# Generated by Django 4.2 on 2023-04-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0002_alter_products_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='sold',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
