# Generated by Django 4.2 on 2023-05-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0003_products_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
