# Generated by Django 4.2 on 2023-05-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0004_products_discount_products_price_products_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
