# Generated by Django 4.2 on 2023-05-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0007_remove_products_discount_remove_products_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='end_auction',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='start_auction',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
