# Generated by Django 4.2 on 2023-05-07 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0008_alter_products_end_auction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='current_price',
            new_name='auction_price',
        ),
    ]
