# Generated by Django 4.2 on 2023-05-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0009_rename_current_price_products_auction_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionproduct',
            name='is_success',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
