# Generated by Django 4.2 on 2023-05-12 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0010_auctionproduct_is_success'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctionproduct',
            options={},
        ),
        migrations.AlterModelOptions(
            name='imageproduct',
            options={},
        ),
        migrations.AlterModelTable(
            name='auctionproduct',
            table='auction_products',
        ),
        migrations.AlterModelTable(
            name='imageproduct',
            table='image_products',
        ),
    ]
