# Generated by Django 4.2 on 2023-05-12 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0011_alter_auctionproduct_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='end_auction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='start_auction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
