# Generated by Django 4.2 on 2023-05-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0012_alter_products_end_auction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionproduct',
            old_name='price_auction',
            new_name='auction_price',
        ),
        migrations.AlterField(
            model_name='products',
            name='end_auction',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='start_auction',
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
