# Generated by Django 4.2 on 2023-05-13 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0013_rename_price_auction_auctionproduct_auction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='is_success',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
