# Generated by Django 4.2 on 2023-05-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0014_alter_auctionproduct_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='auction_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='auctionproduct',
            name='is_success',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
