# Generated by Django 4.2 on 2023-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0015_alter_auctionproduct_auction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='auction_price',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.FloatField(blank=True, max_length=256, null=True),
        ),
    ]
