# Generated by Django 4.2 on 2023-05-29 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0016_alter_products_auction_price_alter_products_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionproduct',
            name='auction_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='auction_price',
            field=models.FloatField(blank=True, default=0, max_length=256, null=True),
        ),
    ]
