# Generated by Django 4.2 on 2023-05-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_product', '0017_alter_auctionproduct_auction_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='auction_price',
            field=models.FloatField(default=0, max_length=256),
        ),
    ]
