# Generated by Django 4.2 on 2023-05-01 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0003_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
