# Generated by Django 4.2 on 2023-05-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0005_alter_author_create_at_alter_role_create_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default='No Name', max_length=256, null=True),
        ),
    ]
