# Generated by Django 4.2 on 2023-05-28 12:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api_auth', '0006_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('work_from', models.CharField(blank=True, max_length=256, null=True)),
                ('birthday', models.CharField(blank=True, max_length=256, null=True)),
                ('role', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert', to='api_auth.role')),
            ],
            options={
                'db_table': 'experts',
            },
        ),
    ]
