# Generated by Django 4.2 on 2023-06-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_auth", "0009_user_is_completed_user_visa_card_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
